services:
  server:
      build:
        context: .
      env_file:
        - .env.docker
      ports:
        - 4000:4000
  db:
    image: mongo:latest
    container_name: node_db
    ports:
      - 27017:27017
    volumes:
      - node_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  cache:
    image: redis:latest
    container_name: node_cache
    ports:
      - "6379:6379"

volumes:
  node_db:
